const stringArray = { type: "array", items: { type: "string" } } as const;

const vocabularyItem = {
  type: "object",
  additionalProperties: false,
  required: ["term", "meaning", "example"],
  properties: {
    term: { type: "string" },
    meaning: { type: "string" },
    example: { type: "string" },
  },
} as const;

export const lessonDraftJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "id",
    "requestId",
    "contentHash",
    "title",
    "language",
    "dialect",
    "level",
    "duration",
    "visualStyle",
    "studentProfile",
    "objectives",
    "screens",
    "sourceMode",
    "createdAt",
    "suggestedNextLesson",
    "levelSignals",
  ],
  properties: {
    schemaVersion: { type: "integer", enum: [1] },
    id: { type: "string" },
    requestId: { type: "string" },
    contentHash: { type: "string" },
    title: { type: "string" },
    language: { type: "string" },
    dialect: { type: "string" },
    level: { type: "string", enum: ["A0", "A1", "A2", "B1", "B2", "C1", "C2"] },
    duration: { type: "integer", minimum: 20, maximum: 120 },
    visualStyle: { type: "string", enum: ["light-editorial", "clean-classroom", "editorial", "dark-debate", "travel", "corporate", "retro-game"] },
    studentProfile: { type: "string" },
    objectives: stringArray,
    screens: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "type",
          "title",
          "instruction",
          "body",
          "prompts",
          "vocabulary",
          "answers",
          "teacherNotes",
          "timing",
          "layout",
          "sourceExcerpt",
          "videoId",
        ],
        properties: {
          id: { type: "string" },
          type: {
            type: "string",
            enum: [
              "cover",
              "objective",
              "warmup",
              "context",
              "source",
              "video",
              "comprehension",
              "vocabulary",
              "pronunciation",
              "sentence-frames",
              "microgrammar",
              "controlled-practice",
              "error-correction",
              "personal-questions",
              "discussion",
              "debate",
              "review",
              "exit-task",
              "homework",
              "answer-key",
            ],
          },
          title: { type: "string" },
          instruction: { type: "string" },
          body: { type: "string" },
          prompts: stringArray,
          vocabulary: { type: "array", items: vocabularyItem },
          answers: stringArray,
          teacherNotes: stringArray,
          timing: { type: "integer" },
          layout: {
            type: "string",
            enum: ["cover", "objective", "comparison", "rule-cards", "example-gallery", "vocabulary-cards", "illustrated-context", "sentence-builder", "multiple-choice", "sorting", "fill-gap", "error-correction", "dialogue", "pronunciation", "personal-prompts", "debate-cards", "recap", "homework", "topic-menu", "image-topic", "verb-bank", "connector-bank", "guided-questions", "feedback"],
          },
          sourceExcerpt: { type: "string" },
          videoId: { type: "string" },
        },
      },
    },
    sourceMode: { type: "string", enum: ["idea", "text", "video"] },
    createdAt: { type: "string" },
    suggestedNextLesson: { type: "string" },
    levelSignals: stringArray,
  },
} as const;
